title: "Solaria Labs VN3 License"
description: "Official VN3 license documents and changelog for Solaria Labs assets."
baseurl: "/vn3-license-solarialabs" # set to "" if you publish on a user page (https://auzlex.github.io)
url: "https://auzlex.github.io"
theme: minima
markdown: kramdown
collections:
  posts:
    output: true
