title: "Solaria Labs VN3 License"
description: "Official VN3 license documents and changelog for Solaria Labs assets."
baseurl: "/vn3-license-solarialabs"
url: "https://auzlex.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-paginate
collections:
  posts:
    output: true
paginate: 5
paginate_path: "/page:num/"
